/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CrankcaseAudio.Wrappers {

public enum ModelFixupError {
  ModelFixupError_NullModel,
  ModelFixupError_VersionIncompatible,
  ModelFixupError_HeaderInvalid
}

}
