/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CrankcaseAudio.Wrappers {

using System;
using System.Runtime.InteropServices;

public partial class PhysicsUpdateParams : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PhysicsUpdateParams(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PhysicsUpdateParams obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PhysicsUpdateParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CrankcaseAudioPINVOKE.delete_PhysicsUpdateParams(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PhysicsUpdateParams() : this(CrankcaseAudioPINVOKE.new_PhysicsUpdateParams(), true) {
  }

  public float Throttle {
    set {
      CrankcaseAudioPINVOKE.PhysicsUpdateParams_Throttle_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.PhysicsUpdateParams_Throttle_get(swigCPtr);
      return ret;
    } 
  }

  public float Break {
    set {
      CrankcaseAudioPINVOKE.PhysicsUpdateParams_Break_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.PhysicsUpdateParams_Break_get(swigCPtr);
      return ret;
    } 
  }

}

}
