/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CrankcaseAudio.Wrappers {

using System;
using System.Runtime.InteropServices;

public partial class PhysicsOutputParameters : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PhysicsOutputParameters(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PhysicsOutputParameters obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PhysicsOutputParameters() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CrankcaseAudioPINVOKE.delete_PhysicsOutputParameters(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PhysicsOutputParameters() : this(CrankcaseAudioPINVOKE.new_PhysicsOutputParameters(), true) {
  }

  public float Rpm {
    set {
      CrankcaseAudioPINVOKE.PhysicsOutputParameters_Rpm_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.PhysicsOutputParameters_Rpm_get(swigCPtr);
      return ret;
    } 
  }

  public float Throttle {
    set {
      CrankcaseAudioPINVOKE.PhysicsOutputParameters_Throttle_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.PhysicsOutputParameters_Throttle_get(swigCPtr);
      return ret;
    } 
  }

  public int Gear {
    set {
      CrankcaseAudioPINVOKE.PhysicsOutputParameters_Gear_set(swigCPtr, value);
    } 
    get {
      int ret = CrankcaseAudioPINVOKE.PhysicsOutputParameters_Gear_get(swigCPtr);
      return ret;
    } 
  }

  public float Velocity {
    set {
      CrankcaseAudioPINVOKE.PhysicsOutputParameters_Velocity_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.PhysicsOutputParameters_Velocity_get(swigCPtr);
      return ret;
    } 
  }

}

}
