/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace CrankcaseAudio.Wrappers {

using System;
using System.Runtime.InteropServices;

public partial class VehiclePhysicsControlData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VehiclePhysicsControlData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(VehiclePhysicsControlData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~VehiclePhysicsControlData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CrankcaseAudioPINVOKE.delete_VehiclePhysicsControlData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public VehiclePhysicsControlData() : this(CrankcaseAudioPINVOKE.new_VehiclePhysicsControlData(), true) {
  }

  public void SetGearRatio(int i, float value) {
    CrankcaseAudioPINVOKE.VehiclePhysicsControlData_SetGearRatio(swigCPtr, i, value);
  }

  public float GetGearRatio(int i) {
    float ret = CrankcaseAudioPINVOKE.VehiclePhysicsControlData_GetGearRatio(swigCPtr, i);
    return ret;
  }

  public ushort EndianStatus {
    set {
      CrankcaseAudioPINVOKE.VehiclePhysicsControlData_EndianStatus_set(swigCPtr, value);
    } 
    get {
      ushort ret = CrankcaseAudioPINVOKE.VehiclePhysicsControlData_EndianStatus_get(swigCPtr);
      return ret;
    } 
  }

  public float Weight {
    set {
      CrankcaseAudioPINVOKE.VehiclePhysicsControlData_Weight_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.VehiclePhysicsControlData_Weight_get(swigCPtr);
      return ret;
    } 
  }

  public float EngineTorque {
    set {
      CrankcaseAudioPINVOKE.VehiclePhysicsControlData_EngineTorque_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.VehiclePhysicsControlData_EngineTorque_get(swigCPtr);
      return ret;
    } 
  }

  public float BreakingHorsePower {
    set {
      CrankcaseAudioPINVOKE.VehiclePhysicsControlData_BreakingHorsePower_set(swigCPtr, value);
    } 
    get {
      float ret = CrankcaseAudioPINVOKE.VehiclePhysicsControlData_BreakingHorsePower_get(swigCPtr);
      return ret;
    } 
  }

  public int GetDataSize() {
    int ret = CrankcaseAudioPINVOKE.VehiclePhysicsControlData_GetDataSize(swigCPtr);
    return ret;
  }

  public void FixupEndian() {
    CrankcaseAudioPINVOKE.VehiclePhysicsControlData_FixupEndian(swigCPtr);
  }

}

}
